import React,{useMemo,useRef,useState}from'react';
import{ArrowLeft,ArrowRight,ChevronDown,FileText,FolderPlus,Lightbulb,Pin,Plus,Sparkles,Trash2}from'lucide-react';
import{diagnose,questions,Reflection,score}from'./editor';
import'./idea-workspace.css';

type Card={id:number;raw:string;title:string;status:string;reflection:Reflection;note?:string;folder?:string;pinned?:boolean};
const empty:Reflection={event:'',detail:'',before:'',after:'',insight:'',audience:'',action:'',change:''};
const seed:Card[]=[{id:1,raw:'最近疯狂逛 MUJI，明明没有什么需要买，每次进去还是觉得特别爽。',title:'MUJI 为什么让我这么舒服？',status:'未整理',reflection:{...empty}},{id:2,raw:'市面上的儿童 AI 玩具怎么都有屏幕？我想给女儿做一个能聊天讲故事、但没有屏幕的。',title:'无屏幕的 AI 儿童玩具',status:'未整理',reflection:{...empty}},{id:3,raw:'最近买回来的衣服几乎全是软软烂烂、像睡衣一样的东西。',title:'最近买的衣服怎么全像睡衣？',status:'未整理',reflection:{...empty}}];
const load=()=>{try{return(JSON.parse(localStorage.getItem('idea-pool')||'null')||seed)as Card[]}catch{return seed}};
const loadFolders=()=>{try{return JSON.parse(localStorage.getItem('idea-folders')||'null')||['主线','轻内容']}catch{return['主线','轻内容']}};
const hasAnswers=(c:Card)=>Object.values(c.reflection||{}).some(v=>String(v||'').trim());

export default function IdeaWorkspace(){
 const[cards,setCards]=useState<Card[]>(load);const[folders,setFolders]=useState<string[]>(loadFolders);const[raw,setRaw]=useState('');const[activeId,setActiveId]=useState<number|null>(null);const[step,setStep]=useState(0);const[screen,setScreen]=useState<'reflect'|'result'|'detail'>('reflect');const[swiped,setSwiped]=useState<number|null>(null);const touchX=useRef(0);const pressTimer=useRef<number>();
 const active=cards.find(c=>c.id===activeId)||null;const result=useMemo(()=>active?diagnose(active.reflection):null,[active]);const points=useMemo(()=>active?score(active.reflection):null,[active]);
 const persist=(next:Card[])=>{setCards(next);localStorage.setItem('idea-pool',JSON.stringify(next))};
 const patchCard=(id:number,patch:Partial<Card>)=>persist(cards.map(c=>c.id===id?{...c,...patch}:c));
 const updateReflection=(patch:Partial<Reflection>)=>{if(!active)return;patchCard(active.id,{reflection:{...active.reflection,...patch},status:'思考中'})};
 const open=(c:Card)=>{setActiveId(c.id);setStep(0);setScreen(hasAnswers(c)&&c.status!=='思考中'?'result':'reflect');setSwiped(null)};
 const backHome=()=>{setActiveId(null);setStep(0);setScreen('reflect')};
 const togglePin=(id:number)=>{const c=cards.find(x=>x.id===id);if(c)patchCard(id,{pinned:!c.pinned});setSwiped(null)};
 const remove=(id:number)=>{if(confirm('删除这条观察？删除后无法恢复。'))persist(cards.filter(c=>c.id!==id));setSwiped(null)};
 const addFolder=()=>{const name=prompt('新文件夹名称');if(!name?.trim()||folders.includes(name.trim()))return;const next=[...folders,name.trim()];setFolders(next);localStorage.setItem('idea-folders',JSON.stringify(next))};
 const groups=useMemo(()=>{const sorted=[...cards].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.id-a.id);const names=['未分组',...folders.filter(f=>sorted.some(c=>c.folder===f))];return names.map(name=>({name,items:sorted.filter(c=>name==='未分组'?!c.folder:c.folder===name)})).filter(g=>g.items.length)},[cards,folders]);

 if(active){
  if(screen==='detail')return <><button className="back" onClick={()=>setScreen('result')}><ArrowLeft size={18}/>返回结果</button><section className="ideaDetail"><p className="eyebrow">完整详情</p><h1>{active.title}</h1><p className="rawQuote">{active.raw}</p><div className="detailAnswers">{questions.map(q=>q.key==='contrast'?<article key={q.key}><b>{q.title}</b><p>我原来以为：{active.reflection.before||'—'}</p><p>但后来发现：{active.reflection.after||'—'}</p></article>:<article key={q.key}><b>{q.title}</b><p>{String((active.reflection as any)[q.key]||'—')}</p></article>)}</div>{active.note&&<article className="detailNote"><b>零碎备注</b><p>{active.note}</p></article>}</section></>;
  if(screen==='result')return <><button className="back" onClick={backHome}><ArrowLeft size={18}/>最近的观察</button><section className="result"><p className="eyebrow"><Sparkles size={15}/>个人内容编辑</p><h1>{result?.type}</h1><div className="score"><strong>{points?.total}</strong><span>/ 12 内容体检</span></div><div className="diagnosis"><article><b>最有价值的东西</b><p>{result?.strongest}</p></article><article><b>当前最大的问题</b><p>{result?.problem}</p></article><article><b>这一篇只抓什么</b><p className="focusline">{result?.focus}</p></article><article><b>下一步</b><p>{result?.next}</p></article></div><section className="cardTools"><label>放进文件夹<div className="selectWrap"><select value={active.folder||''} onChange={e=>patchCard(active.id,{folder:e.target.value||undefined})}><option value="">未分组</option>{folders.map(f=><option key={f}>{f}</option>)}</select><ChevronDown size={15}/></div></label><button className="textButton" onClick={addFolder}><FolderPlus size={16}/>新建文件夹</button></section><label className="noteBox"><span>零碎备注</span><textarea value={active.note||''} onChange={e=>patchCard(active.id,{note:e.target.value})} placeholder="临时想到的例子、标题、拍摄画面……都可以先放这里。"/></label><div className="resultActions"><button className="secondary" onClick={()=>{setScreen('reflect');setStep(0)}}>继续修改</button><button className="secondary" onClick={()=>setScreen('detail')}><FileText size={16}/>详情展示</button><button onClick={()=>{patchCard(active.id,{status:result?.type==='继续观察'?'继续观察':'候选选题'});backHome()}}>保存</button></div></section></>;
  const q=questions[step];return <><button className="back" onClick={backHome}><ArrowLeft size={18}/>观察池</button><section className="focus"><div className="progress"><span>{step+1} / 7</span><i style={{width:`${(step+1)/7*100}%`}}/></div><p className="eyebrow">想一想</p><h1>{q.title}</h1><p className="hint">{q.hint}</p>{q.key==='contrast'?<div className="contrast"><label>我原来以为<textarea value={active.reflection.before} onChange={e=>updateReflection({before:e.target.value})}/></label><label>但后来发现<textarea value={active.reflection.after} onChange={e=>updateReflection({after:e.target.value})}/></label></div>:<textarea className="answer" autoFocus value={(active.reflection as any)[q.key]} onChange={e=>updateReflection({[q.key]:e.target.value}as any)} placeholder="写下真实的东西，不需要写得漂亮。"/>}<div className="nav">{step>0?<button className="secondary" onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>上一步</button>:<span/>}<button onClick={()=>step<6?setStep(step+1):setScreen('result')}>{step<6?'下一步':'让编辑看看'}<ArrowRight size={17}/></button></div></section></>;
 }

 return <><header><p className="eyebrow">选题观察池</p><h1>刚刚发生了什么，<br/>让你有感觉？</h1><p>先记录生活，不要急着想“这个怎么发”。</p></header><section className="capture"><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder="好爽、好烦、好奇怪、居然可以这样……"/><button onClick={()=>{if(!raw.trim())return;const text=raw.trim();persist([{id:Date.now(),raw:text,title:text.length>28?text.slice(0,28)+'…':text,status:'未整理',reflection:{...empty}},...cards]);setRaw('')}}><Plus size={18}/>记下来</button></section><section className="list"><div className="listhead"><div><h2>最近的观察</h2><small>左滑删除 · 长按置顶</small></div><button className="folderButton" onClick={addFolder}><FolderPlus size={16}/>文件夹</button></div>{groups.map(group=><section className="folderGroup" key={group.name}><h3>{group.name}<span>{group.items.length}</span></h3>{group.items.map(c=><div className={`swipeRow ${swiped===c.id?'open':''}`} key={c.id}><div className="rowActions"><button onClick={()=>togglePin(c.id)} aria-label="置顶"><Pin size={17}/></button><button className="delete" onClick={()=>remove(c.id)} aria-label="删除"><Trash2 size={17}/></button></div><button className="card" onTouchStart={e=>{touchX.current=e.touches[0].clientX;pressTimer.current=window.setTimeout(()=>togglePin(c.id),650)}} onTouchMove={e=>{if(Math.abs(e.touches[0].clientX-touchX.current)>10)clearTimeout(pressTimer.current)}} onTouchEnd={e=>{clearTimeout(pressTimer.current);if(e.changedTouches[0].clientX-touchX.current<-45)setSwiped(c.id);else if(e.changedTouches[0].clientX-touchX.current>35)setSwiped(null)}} onPointerDown={e=>{if(e.pointerType==='mouse')pressTimer.current=window.setTimeout(()=>togglePin(c.id),650)}} onPointerUp={()=>clearTimeout(pressTimer.current)} onPointerLeave={()=>clearTimeout(pressTimer.current)} onClick={()=>open(c)}><div>{c.pinned&&<span className="pinBadge"><Pin size={11}/>置顶</span>}<span className={`tag ${c.status}`}>{c.status}</span><h3>{c.title}</h3><p>{c.raw}</p></div><ArrowRight size={18}/></button></div>)}</section>)}</section></>;
}

